#==================================================
# S W I N G   G U I   L O C A L I S A T I O N

appTabbedPane.information.tabTitle=Informations
appTabbedPane.information.IPlookUp=Do name lookup on IP addresses (may be slow)
appTabbedPane.information.updating=Updating...

appTabbedPane.logConfiguration.tabTitle=Log configuration
appTabbedPane.logConfiguration.selectLogger=Select the logger from the following root:
appTabbedPane.logConfiguration.configureLogger=Configure logger 

appTabbedPane.logDisplay.tabTitle=Log display
appTabbedPane.logDisplay.currentTabName=current
appTabbedPane.logDisplay.searchButton=Search
appTabbedPane.logDisplay.resetButton=Reset
appTabbedPane.logDisplay.caseSensitiveCheckBox=Case sensitive
appTabbedPane.logDisplay.ignoreAccentsCheckBox=Ignore accents
appTabbedPane.logDisplay.ignoreFormattingCheckBox=Ignore formatting
appTabbedPane.logDisplay.showCategoriesButton=Show categories
appTabbedPane.logDisplay.resetHighlightButton=Reset highlight
appTabbedPane.logDisplay.nextButton=next
appTabbedPane.logDisplay.previousButton=previous
appTabbedPane.logDisplay.occurence=occurence
appTabbedPane.logDisplay.occurences=occurences
appTabbedPane.logDisplay.of=of
appTabbedPane.logDisplay.nooccurence=no occurence
