#
# S A M P L E   P R O P E R T I E S   U S E D   B Y  FlUtils
# ----------------------------------------------------------

#==================================================
#   L O G G I N G
# Logging file (for errors, info ...)
# Defined in a separate property file according to java.util.logging.LogManager
# Must be accessible by class loder (may be put in src/main/java folder)
logManager.properties.file=loggingProperties_Sample.properties

# Formatter for specific handlers (GUI logging, custom formatter)
# Available Formatters
#   java.util.logging.SimpleFormatter
#   java.util.logging.XMLFormatter
#   org.fl.util.PlainLogFormatter
#   org.fl.util.JsonLogFormatter
logging.formatter=org.fl.util.PlainLogFormatter

#----------------------------------------------------------------------
# in Memory logging for the application 
# bufferLength is the maximum number of log records
# Typically used in real time apps. Accessing logs may be achieved with application like webAppliAdminGui 
# logging.BufferLogHandler.bufferLength=100
# logging.BufferLogHandler.level=INFO

# in memory logging handler reserved for application initialization
# Used before the GUI setup
# Once the GUI is set up, the eventual log records will be displayed in the Log Display tab
# bufferLength is the maximum number of log records
# Typically used in real time apps. Accessing logs may be achieved with application like webAppliAdminGui 
logging.BufferLogHandlerForInit.bufferLength=40
logging.BufferLogHandlerForInit.level=INFO

# sample properties for custom handler CloudantLogHandler
#logging.CloudantLogHandler.encode=UTF-8
#logging.CloudantLogHandler.level=INFO

#==================================================
# S W I N G   G U I

appTabbedPane.locale.language=fr
appTabbedPane.locale.country=FR
appTabbedPane.logging.lastNonHighLighedLevel=INFO
appTabbedPane.logging.recordHighLightColor=PINK
appTabbedPane.logging.logTabHighLightColor=RED

appTabbedPane.logging.logDisplayMaxLength=100000
appTabbedPane.logging.subTabNumber=3
appTabbedPane.logging.logTabSelectedColor=GREEN
appTabbedPane.logging.searchHighLightColors=CYAN,LIGHT_GRAY,YELLOW,MAGENTA

# If true, at the start of the application, all JVM, system and application properties will be logged
runningContext.operatingInfo.log=true
