version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${flutils.build.user.name}
builderEmail=${flutils.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${flutils.branch}
gitCommitIdDescribe=${flutils.commit.id.describe}
gitCommitId=${flutils.commit.id.full}
gitCommitUrl=${flutils.remote.origin.url}
gitCommitTime=${flutils.commit.time}
gitDirty=${flutils.dirty}