/*
 * MIT License

Copyright (c) 2017, 2025 Frederic Lefevre

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package org.fl.util;

import java.io.IOException;
import java.io.StringReader;
import java.net.URI;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Enumeration;
import java.util.Optional;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Formatter;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.fl.util.file.FilesUtils;
import org.fl.util.json.JsonUtils;
import org.fl.util.os.OperatingInfo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.javaprop.JavaPropsMapper;

/*
# Properties for RunningContext 
#
runningContext.operatingInfo.log=true
 */

public class RunningContext {

	private static final String DEFAULT_APP_NAME = "org.fl";
	
	private static final String projectBuildPropertyFile = "project.properties";

	private static final String DATE_PATTERN = "uuuu-MM-dd HH:mm:ss.SSS VV";

	// Root logger
	private static final Logger rootLogger = Logger.getLogger("");
	
	private static final JavaPropsMapper propsMapper = new JavaPropsMapper();

	private final String name;
	private Logger applicationRootLog;
	private AdvancedProperties applicationProperties;
	private PropertiesStorage propsStorage;
	private LoggerManager logMgr;
	private Instant initializationDate;

	private ArrayNode buildInformation;
	private JsonNode loggingPropertiesAsJson;
	
	/**
	 * @param name : normally named, using a hierarchical dot-separated namespace. 
	 * That name will be used to configure Logger, so it should normally be based on the application package name
	 * @param systemProperty : System property name containing the property file url
	 * @param defaultPropertyUri : Default property file url, if the system property containing the property file uri is null
	 *         The property file may denominated by :
     *  		- a well formed URI (for instance "http://my.server.org/myProps.properties" or "file:///my/dir/myProps.properties")
	 */
	public RunningContext(String name, String systemProperty, URI defaultPropertyUri) {
		
		if (name == null) {
			this.name = DEFAULT_APP_NAME;
			rootLogger.severe("Null application name passed in running context");
		} else {
			this.name = name;		
		}	
		
		try {
			propsStorage = new PropertiesStorage(systemProperty, defaultPropertyUri);
			initRunningContext(this.name, systemProperty) ;
		} catch (Exception e) {
			rootLogger.log(Level.SEVERE, "Exception processing property file.  ", e);
			applicationProperties = new AdvancedProperties(rootLogger) ;			
		}
	}
	
	public String getName() {
		return name;
	}
	
	public String getBuildInformation() throws JsonProcessingException {
		return JsonUtils.jsonPrettyPrint(buildInformation);
	}
	
	public JsonNode getBuildInformationAsJson() throws JsonProcessingException {
		return buildInformation;
	}
	
	private void initRunningContext(String name, String systemProperty) {
		
		initializationDate = Instant.now();

		// get property file
		applicationProperties = propsStorage.getAdvanced(rootLogger); 

		// Initialize logger
		logMgr = LoggerManager.builder()
				.applicationRootLoggerName(name)
				.properties(applicationProperties)
				.build();

		applicationRootLog = Logger.getLogger(this.name);
		
		// eventually get the property file generated by the build
		buildInformation = JsonNodeFactory.instance.arrayNode();
		addBuildInformation(name, true);
		addBuildInformation("org.fl.util", false);

		// Get the java.util.logging properties as Json
		loggingPropertiesAsJson = getLoggingProperties();
		
		boolean logOperatingInfos = applicationProperties.getBoolean("runningContext.operatingInfo.log", false);
		if (logOperatingInfos) {
			applicationRootLog.info(getOperatingInfos(true).toString());
		}

	}
	
	public void addBuildInformation(String moduleName) {
		addBuildInformation(moduleName, false);
	}
	
	private void addBuildInformation(String moduleName, boolean addToApplicationProps) {
		
		JsonNode moduleBuildInfo = getBuildInformation(moduleName, true);
		if (moduleBuildInfo != null) {
			buildInformation.add(moduleBuildInfo);
		} else {
			buildInformation.add(
				JsonNodeFactory.instance.objectNode()
					.put("moduleName", moduleName)
					.put("buildInformation", "No build information")
			);
		}
	}
	
	private JsonNode getBuildInformation(String moduleName, boolean addToApplicationProps) {
		
		try {

			String propsProjectString = findProjectProperties(moduleName); 

			if (propsProjectString != null) {
				
				if (addToApplicationProps) {
					Properties propsProject = new Properties();
					propsProject.load(new StringReader(propsProjectString));
					applicationProperties.putAll(propsProject);
				}

				ObjectNode moduleBuildInformation = (ObjectNode)propsMapper.readTree(propsProjectString);
				moduleBuildInformation.put("moduleName", moduleName);
				return moduleBuildInformation;

			} else {
				return null;
			}
		} catch (Exception e) {
			applicationRootLog.log(Level.WARNING, "Exception looking for build information for " + moduleName, e);
			return null;
		}
	}
	
	private String findProjectProperties(String name) {
		
		try {
			String projectPropRelativeName = name + "_" + projectBuildPropertyFile;
			
			URL projectPropUrl = Optional
					.ofNullable(RunningContext.class.getClassLoader().getResource(projectPropRelativeName))
					.orElseGet(() -> {
						applicationRootLog.warning("Specific project property file not found: " + projectPropRelativeName);
						applicationRootLog.warning("Project property file fallback: " + projectBuildPropertyFile);
						return RunningContext.class.getClassLoader().getResource(projectBuildPropertyFile);
					});

			if (projectPropUrl != null) {
				return new String(projectPropUrl.openStream().readAllBytes(), StandardCharsets.UTF_8);	
			} else {
				applicationRootLog.warning("No project properties (build information) found");
				return null;
			}
			
		} catch (Exception e) {
			applicationRootLog.log(Level.WARNING, "Exception looking for build information for " + name, e);
			return null;
		}
	}

	private JsonNode getLoggingProperties() {
		
		Properties loggingProperties = logMgr.getLoggingProperties();
		if (loggingProperties != null) {
			
			try {
				return propsMapper.readPropertiesAs(loggingProperties, JsonNode.class);
			} catch (IOException e) {
				applicationRootLog.log(Level.WARNING, "Exception looking for logging properties for " + name, e);
				return null;
			}
		} else {
			return null;
		}
	}
	
	public AdvancedProperties getProps() {
		return applicationProperties;
	}
	
	public Formatter getCommonLogFormatter() {
		return logMgr.getCommonFormatterInstance();
	}
	
	public void addCustomLogHandler(Handler customLogHandler) {
		
		if (logMgr != null) {
			logMgr.addCustomHandler(customLogHandler);
		}
	}
	
	// Set the level of logger and log handlers
	public boolean setLogsLevel(JsonNode levelsJson) {

		if (logMgr != null) {
			return logMgr.setLogsLevels(levelsJson);
		} else {
			return false;
		}
	}
	
	public JsonNode getLogsLevel() {

		if (logMgr != null) {
			return logMgr.getLoggerLevels();
		} else {
			// No logger manager, return an empty JsonObject
			return JsonNodeFactory.instance.objectNode();
		}
	}

	public URL getPropertiesLocation() {
		return propsStorage.getPropertyLocation();
	}

	public StringBuilder getMemoryLogs() {
		return logMgr.getMemoryLogs();
	}

	public String deleteMemoryLogs() {
		return logMgr.deleteMemoryLogs();
	}

	public String deleteAndResizeMemoryLogs(int newsize) {
		return logMgr.deleteMemoryLogsAndResize(newsize);
	}

	public Instant getInitializationDate() {
		return initializationDate;
	}
	
	public String printInitializationDate() {
		return DateTimeFormatter.ofPattern(DATE_PATTERN).format(ZonedDateTime.ofInstant(initializationDate, ZoneId.systemDefault()));
	}
	
	public JsonNode getOperatingInfos(boolean withIpLookup) {
		return (new OperatingInfo()).getInfo(withIpLookup);
	}

	public JsonNode getApplicationInfo(boolean withIpLookup) {

		ObjectNode applicationInfo = JsonNodeFactory.instance.objectNode();
		String initDate = printInitializationDate();
		JsonNode operatingContext = getOperatingInfos(withIpLookup);

		URL propsLocation = getPropertiesLocation();
		if (propsLocation != null) {
			applicationInfo.put("propertiesLocation", propsLocation.toString());
		} else {
			applicationInfo.put("propertiesLocation", "No properties file location");
		}
		if ((buildInformation != null) && !buildInformation.isEmpty()) {
			applicationInfo.set("buildInformation", buildInformation);
		} else {
			applicationInfo.put("buildInformation", "No build information");
		}
		
		if ((loggingPropertiesAsJson != null) && !loggingPropertiesAsJson.isEmpty()) {
			applicationInfo.set("loggingInformation", loggingPropertiesAsJson);
		} else {
			applicationInfo.put("loggingInformation", "No java.util.logging information");
		}
		
		applicationInfo.put("initialisationDate", initDate);
		applicationInfo.set("applicationProperties", getPropertiesAsJson());
		applicationInfo.set("operatingContext", operatingContext);
		applicationInfo.set("fileSystemsInformation", FilesUtils.getFileSystemsInformation(applicationRootLog));

		return applicationInfo;
	}

	public JsonNode getPropertiesAsJson() {

		Enumeration<Object> keys = applicationProperties.keys();
		Vector<String> keyList = new Vector<String>();
		while (keys.hasMoreElements()) {
			keyList.add((String) keys.nextElement());
		}
		Collections.sort(keyList);
		ObjectNode applicationPropsNode = JsonNodeFactory.instance.objectNode();
		keyList.forEach(key -> applicationPropsNode.put(key, applicationProperties.getProperty(key)));

		return applicationPropsNode;
	}

}
